<a href="https://colab.research.google.com/github/janeurieta/TallerPythonIntroCienciaDatos/blob/master/Tarea_curso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python básico para físicos
## Valeria Yanet Urieta de la Cruz

### Problema [1](https://codeforces.com/problemset/problem/4/A):  **Sandía**



In [75]:
def generaPares(m):
  n=1
  lista=[]
  while n<=m:
    lista.append(n*2)
    n+=1
  return lista
print(generaPares(50))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


Dame el peso w de la sandia

In [79]:
print("Dame el peso w de la sandia") 

Dame el peso w de la sandia


In [87]:
w = 5 

existe = w in generaPares(50) 

print("SI".format(w, existe) ) 

SI


In [88]:
w = 50
if w in range(0, 101): # si w está en el rango 1 - 100
    print("SI")
else:
    print("NO")

SI


### Problema [2](https://codeforces.com/problemset/problem/339/A): **Ayuda Matemática**

In [82]:
numeros = [1,3,1,1,1,3,2,2,3,1,1,2,3,1,3,2,1]

In [85]:
numeros.sort()  
print(numeros)

[1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3]


In [86]:
suma = sum(numeros)

print("La suma de todos los elementos es ", suma)

La suma de todos los elementos es  31


### Problema 3: **Mecánica cuántica**

In [106]:
import sympy as sp
sp.init_printing()

Hallar el valor esperado de la energía para el sistema. 

In [109]:
E_0 = sp.symbols('E_0',positive = True)

H = E_0*sp.Matrix([[0,sp.I,0],
              [-sp.I,0,0],
              [0,0,-1]])
H

⎡  0    ⅈ⋅E₀   0 ⎤
⎢                ⎥
⎢-ⅈ⋅E₀   0     0 ⎥
⎢                ⎥
⎣  0     0    -E₀⎦

In [111]:
from sympy.physics.quantum.dagger import Dagger


In [112]:
H_conj = Dagger(H)
H_conj == H

True

In [113]:
H.eigenvals()

In [114]:
H_ener = list(H.eigenvals().keys())
H_ener


In [115]:
H.eigenvects()

⎡⎛        ⎡⎡-ⅈ⎤  ⎡0⎤⎤⎞  ⎛       ⎡⎡ⅈ⎤⎤⎞⎤
⎢⎜        ⎢⎢  ⎥  ⎢ ⎥⎥⎟  ⎜       ⎢⎢ ⎥⎥⎟⎥
⎢⎜-E₀, 2, ⎢⎢1 ⎥, ⎢0⎥⎥⎟, ⎜E₀, 1, ⎢⎢1⎥⎥⎟⎥
⎢⎜        ⎢⎢  ⎥  ⎢ ⎥⎥⎟  ⎜       ⎢⎢ ⎥⎥⎟⎥
⎣⎝        ⎣⎣0 ⎦  ⎣1⎦⎦⎠  ⎝       ⎣⎣0⎦⎦⎠⎦

In [116]:
aux1 = H.eigenvects()[0][2]
aux2 = H.eigenvects()[1][2][0]

H_vecp = [aux1,aux2]
H_vecp

⎡⎡⎡-ⅈ⎤  ⎡0⎤⎤  ⎡ⅈ⎤⎤
⎢⎢⎢  ⎥  ⎢ ⎥⎥  ⎢ ⎥⎥
⎢⎢⎢1 ⎥, ⎢0⎥⎥, ⎢1⎥⎥
⎢⎢⎢  ⎥  ⎢ ⎥⎥  ⎢ ⎥⎥
⎣⎣⎣0 ⎦  ⎣1⎦⎦  ⎣0⎦⎦

In [117]:
H*H_vecp[1] == E_0*H_vecp[1]

True

In [118]:
ket = 1/sp.sqrt(5)*sp.Matrix([1-sp.I,1-sp.I,1])
ket


⎡√5⋅(1 - ⅈ)⎤
⎢──────────⎥
⎢    5     ⎥
⎢          ⎥
⎢√5⋅(1 - ⅈ)⎥
⎢──────────⎥
⎢    5     ⎥
⎢          ⎥
⎢    √5    ⎥
⎢    ──    ⎥
⎣    5     ⎦

In [119]:
bra = Dagger(ket)
bra

⎡√5⋅(1 + ⅈ)  √5⋅(1 + ⅈ)  √5⎤
⎢──────────  ──────────  ──⎥
⎣    5           5       5 ⎦

In [120]:
sp.simplify(bra*ket)

[1]

In [121]:
bra*H*ket

⎡-E₀ ⎤
⎢────⎥
⎣ 5  ⎦

NUMERICA

In [122]:
A_num = np.array([[-2, -4, 2], 
                  [-2, 1, 2],
                  [4, 2, 5]])

A_num

array([[-2, -4,  2],
       [-2,  1,  2],
       [ 4,  2,  5]])

In [91]:
B_num = np.array([[1, 4, 3],
                  [0, -1, 2], 
                  [1, 2, 5]])

B_num

array([[ 1,  4,  3],
       [ 0, -1,  2],
       [ 1,  2,  5]])

In [92]:

A_num + B_num

array([[-1,  0,  5],
       [-2,  0,  4],
       [ 5,  4, 10]])

In [93]:
A_num*B_num

array([[ -2, -16,   6],
       [  0,  -1,   4],
       [  4,   4,  25]])

In [94]:
np.dot(A_num, B_num)

array([[ 0,  0, -4],
       [ 0, -5,  6],
       [ 9, 24, 41]])

In [95]:
np.linalg.det(A_num)

-90.0

In [96]:
np.linalg.inv(A_num)

array([[-0.01111111, -0.26666667,  0.11111111],
       [-0.2       ,  0.2       , -0.        ],
       [ 0.08888889,  0.13333333,  0.11111111]])

In [97]:
np.linalg.eig(A_num)

(array([-5.,  3.,  6.]), array([[ 0.81649658,  0.53452248,  0.05842062],
        [ 0.40824829, -0.80178373,  0.35052374],
        [-0.40824829, -0.26726124,  0.93472998]]))



### Problema 4:

Buscar datos que sean de su interés$^1$, realizar la limpieza y exploración de datos. Usando Pandas y  Matplotlib como librerías principales. Ver: [Taller 3](https://www.youtube.com/watch?v=XtTgRYnEJJE&t=833s&ab_channel=PythonClubforPhysicists)

También puede buscar sus datos en [Kaggle](https://www.kaggle.com/)

*1. puede usar cualquier fuente (siempre y cuando adjunte sus datos)*